set autoindent
set expandtab
set shiftround
set shiftwidth=4
set tabstop=4

set hlsearch
set ignorecase
set incsearch
set smartcase

set encoding=utf-8
syntax enable

set number
set laststatus=2
set wildmenu
set title
set background=dark
set cursorline

set backupdir=~/.vim/backup
set undodir=~/.vim/undo
set noswapfile

set history=1000

filetype on
filetype indent on

set nowrap
set foldenable
set wildmode=list:longest
set foldmethod=indent
